/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_adapters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adapters/{adapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_adapter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adapters/{adapter_id}/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["run_eval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["budget_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["runtime_config"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_profiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_rubrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_runs"];
        put?: never;
        post: operations["create_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rescore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_run_turns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/turns/{step_index}/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_run_turn_training"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_training_runs"];
        put?: never;
        post: operations["create_training_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/training-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_training_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdapterDetail: {
            adapter: components["schemas"]["AdapterRecord"];
            children: components["schemas"]["AdapterRecord"][];
            eval_reports: components["schemas"]["EvalReport"][];
        };
        AdapterRecord: {
            base_model: string;
            /** Format: date-time */
            created_at: string;
            /** Format: double */
            eval_score?: number | null;
            id: string;
            metadata: {
                [key: string]: string;
            };
            parent_id?: string | null;
            path: string;
            tags: string[];
            training_run_id?: string | null;
        };
        BTreeMap: {
            [key: string]: boolean | number | string;
        };
        BudgetStatus: {
            /** Format: double */
            cap_usd: number;
            exceeded: boolean;
            /** Format: double */
            remaining_usd?: number | null;
            /** Format: double */
            spent_usd: number;
            /** Format: double */
            window_hours: number;
        };
        CancelResponse: {
            run_id: string;
        };
        CreateRunResponse: {
            run_id: string;
        };
        CreateTrainingRunBody: {
            hyperparams?: components["schemas"]["BTreeMap"];
            parent_adapter_id?: string | null;
            sample_run_ids?: string[];
        };
        CreateTrainingRunResponse: {
            training_run_id: string;
        };
        DashboardSnapshot: {
            /** Format: date-time */
            generated_at: string;
            jobs: components["schemas"]["JobCounts"];
            runs: components["schemas"]["RunManifest"][];
            workers: components["schemas"]["WorkerRecord"][];
        };
        DomainEvent: {
            /** @enum {string} */
            kind: "rollout.queued";
            payload: {
                manifest: components["schemas"]["RunManifest"];
            };
        } | {
            /** @enum {string} */
            kind: "rollout.started";
            payload: {
                manifest: components["schemas"]["RunManifest"];
            };
        } | {
            /** @enum {string} */
            kind: "step.recorded";
            payload: {
                step: components["schemas"]["TrajectoryStep"];
            };
        } | {
            /** @enum {string} */
            kind: "progress.ticked";
            payload: {
                /** Format: double */
                cost_usd: number;
                /** Format: int64 */
                tokens: number;
                tool?: string | null;
                /** Format: int32 */
                turn: number;
            };
        } | {
            /** @enum {string} */
            kind: "reward.computed";
            payload: {
                reward: components["schemas"]["RewardRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "rollout.completed";
            payload: {
                manifest: components["schemas"]["RunManifest"];
            };
        } | {
            /** @enum {string} */
            kind: "rollout.failed";
            payload: {
                error: string;
                manifest: components["schemas"]["RunManifest"];
            };
        } | {
            /** @enum {string} */
            kind: "rollout.cancelled";
            payload: {
                manifest: components["schemas"]["RunManifest"];
            };
        } | {
            /** @enum {string} */
            kind: "budget.exceeded";
            payload: {
                /** Format: double */
                cap_usd: number;
                /** Format: double */
                spent_usd: number;
                /** Format: double */
                window_hours: number;
            };
        } | {
            /** @enum {string} */
            kind: "worker.updated";
            payload: {
                worker: components["schemas"]["WorkerRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "log.line";
            payload: {
                context: {
                    [key: string]: string;
                };
                level: string;
                logger: string;
                message: string;
            };
        } | {
            /** @enum {string} */
            kind: "training.queued";
            payload: {
                record: components["schemas"]["TrainingRunRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "training.started";
            payload: {
                record: components["schemas"]["TrainingRunRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "training.metric";
            payload: {
                metric: components["schemas"]["TrainingMetricPoint"];
            };
        } | {
            /** @enum {string} */
            kind: "training.completed";
            payload: {
                record: components["schemas"]["TrainingRunRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "training.failed";
            payload: {
                error: string;
                record: components["schemas"]["TrainingRunRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "adapter.published";
            payload: {
                adapter: components["schemas"]["AdapterRecord"];
            };
        } | {
            /** @enum {string} */
            kind: "eval.completed";
            payload: {
                report: components["schemas"]["EvalReport"];
            };
        };
        ErrorBody: {
            detail: string;
        };
        EvalReport: {
            adapter_id: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** Format: double */
            mean_reward: number;
            per_task: components["schemas"]["EvalTaskScore"][];
            task_set: string;
        };
        EvalTask: {
            /** Format: int32 */
            horizon?: number;
            id: string;
            prompt: string;
            success_criteria?: string[];
        };
        EvalTaskScore: {
            run_id: string;
            task_id: string;
            /** Format: double */
            terminal_reward: number;
        };
        /** @description An event with its subject, before it is assigned a sequence number. */
        Event: components["schemas"]["DomainEvent"] & {
            /** Format: date-time */
            at: string;
            subject?: null | components["schemas"]["Subject"];
        };
        /**
         * @description One row of the durable event log. `seq` is monotonic per store so
         *     clients can resume a WebSocket with `?since=<seq>`.
         */
        EventEnvelope: components["schemas"]["Event"] & {
            /** Format: int64 */
            seq: number;
        };
        HealthResponse: {
            status: string;
        };
        JobCounts: {
            /** Format: int32 */
            cancelled: number;
            /** Format: int32 */
            completed: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            queued: number;
            /** Format: int32 */
            running: number;
        };
        /** @enum {string} */
        JobKind: "rollout" | "training";
        /**
         * @description A leased unit of work. Rollouts and training runs are both jobs so a
         *     crash mid-run leaves a row another worker can pick up after the lease
         *     expires, instead of an orphaned in-memory task.
         */
        JobRecord: {
            /** Format: int32 */
            attempts: number;
            cancel_requested: boolean;
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            id: string;
            kind: components["schemas"]["JobKind"];
            lease_owner?: string | null;
            /** Format: date-time */
            lease_until?: string | null;
            payload: unknown;
            status: components["schemas"]["JobStatus"];
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        ProfileInfo: {
            api_key_env?: string | null;
            base_url: string;
            env_id?: string | null;
            model: string;
            name: string;
            routes_to: string;
        };
        ProfilesResponse: {
            default: string;
            profiles: components["schemas"]["ProfileInfo"][];
        };
        RescoreResponse: {
            /** Format: double */
            delta?: number | null;
            persisted: boolean;
            previous?: null | components["schemas"]["RewardRecord"];
            reward: components["schemas"]["RewardRecord"];
            rubric: string;
            run_id: string;
        };
        RewardRecord: {
            audit_flags: string[];
            /** @description `heuristic-v1`, `coding-v1`, `verifiers-vf-math`, ... */
            rubric: string;
            signals: components["schemas"]["RewardSignal"][];
            /** @description `rubric` (in-house signals) or `verifiers` (env-owned scoring). */
            source: string;
            /** Format: double */
            terminal_reward: number;
        };
        /** @description One named contribution to a reward. */
        RewardSignal: {
            name: string;
            reason: string;
            /** Format: double */
            value: number;
            /** Format: double */
            weight: number;
        };
        RolloutRequest: {
            adapter_id?: string | null;
            /**
             * Format: int32
             * @description When absent, the configured round scheduler decides the horizon.
             */
            horizon?: number | null;
            infra_target?: string;
            /** @description Named policy profile. Absent = the configured default profile. */
            policy_profile?: string | null;
            prompt: string;
            repo_snapshot?: string;
            success_criteria?: string[];
        };
        RubricInfo: {
            name: string;
            signals: string[];
        };
        RunDetail: {
            manifest: components["schemas"]["RunManifest"];
            reward?: null | components["schemas"]["RewardRecord"];
            task: components["schemas"]["TaskSpec"];
            trajectory: components["schemas"]["Trajectory"];
        };
        RunEvalBody: {
            task_set?: string | null;
            tasks?: components["schemas"]["EvalTask"][] | null;
        };
        RunManifest: {
            adapter_id?: string | null;
            /** Format: double */
            cost_usd: number;
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            /** Format: int32 */
            horizon: number;
            id: string;
            infra_target: string;
            /** @description `openai:<model>` or `verifiers:<env>:<model>`. */
            model_id: string;
            /** @description Policy profile name the run was dispatched with. */
            profile: string;
            status: components["schemas"]["RunStatus"];
            /** Format: int32 */
            step_count: number;
            /** Format: double */
            terminal_reward?: number | null;
            /** Format: int64 */
            tokens: number;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        RunStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        RuntimeConfig: {
            default_profile: string;
            env_backend: string;
            max_parallel_rollouts: number;
            policy_name: string;
            profile_names: string[];
            sandbox: string;
            store_backend: string;
            trainer_backend: string;
            verifiers_env_id?: string | null;
            worker_id: string;
        };
        Subject: {
            id: string;
            /** @enum {string} */
            kind: "run";
        } | {
            id: string;
            /** @enum {string} */
            kind: "training_run";
        } | {
            id: string;
            /** @enum {string} */
            kind: "adapter";
        } | {
            id: string;
            /** @enum {string} */
            kind: "worker";
        };
        /** @description What a rollout is asked to do. */
        TaskSpec: {
            /** Format: int32 */
            horizon: number;
            id: string;
            prompt: string;
            repo_snapshot: string;
            success_criteria: string[];
        };
        TrainingMetricPoint: {
            extra: {
                [key: string]: number;
            };
            /** Format: double */
            kl?: number | null;
            /** Format: double */
            loss: number;
            /** Format: double */
            mean_reward?: number | null;
            /** Format: int32 */
            step: number;
        };
        TrainingRunRecord: {
            adapter_in?: string | null;
            adapter_out?: string | null;
            /** Format: date-time */
            created_at: string;
            error?: string | null;
            hyperparams: components["schemas"]["BTreeMap"];
            id: string;
            metrics: components["schemas"]["TrainingMetricPoint"][];
            sample_run_ids: string[];
            status: components["schemas"]["TrainingStatus"];
            trainer: string;
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        TrainingStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        Trajectory: {
            errors: string[];
            steps: components["schemas"]["TrajectoryStep"][];
        };
        TrajectoryStep: {
            actor: string;
            /** Format: date-time */
            at: string;
            content: string;
            /** @description True when a `TurnTrainingRecord` row exists for this step. */
            has_training_metadata?: boolean;
            /** Format: int32 */
            index: number;
            kind: string;
        };
        TurnIndexEntry: {
            /** Format: date-time */
            created_at: string;
            model_name: string;
            /** Format: int32 */
            step_index: number;
            /** Format: int32 */
            token_count: number;
        };
        /**
         * @description Per-turn token-level metadata, stored in its own table so run payloads
         *     never carry the bytes.
         */
        TurnTrainingRecord: {
            attention_mask?: number[];
            completion_ids?: number[];
            /** Format: date-time */
            created_at?: string;
            id: string;
            loss_mask?: number[];
            model_name?: string;
            prompt_ids?: number[];
            run_id: string;
            sampling_args?: {
                [key: string]: unknown;
            };
            /** Format: int32 */
            step_index: number;
            /** Format: int32 */
            token_count?: number;
        };
        WorkerRecord: {
            detail: string;
            id: string;
            role: string;
            run_id?: string | null;
            status: components["schemas"]["WorkerStatus"];
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        WorkerStatus: "idle" | "running" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_adapters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterRecord"][];
                };
            };
        };
    };
    get_adapter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdapterDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    run_eval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["RunEvalBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReport"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    budget_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetStatus"];
                };
            };
        };
    };
    runtime_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeConfig"];
                };
            };
        };
    };
    dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSnapshot"];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                since?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventEnvelope"][];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRecord"][];
                };
            };
        };
    };
    list_profiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilesResponse"];
                };
            };
        };
    };
    list_rubrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricInfo"][];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunManifest"][];
                };
            };
        };
    };
    create_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolloutRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    cancel_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rescore: {
        parameters: {
            query: {
                rubric: string;
                dry_run?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescoreResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_run_turns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnIndexEntry"][];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_run_turn_training: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnTrainingRecord"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_training_runs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRunRecord"][];
                };
            };
        };
    };
    create_training_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainingRunBody"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTrainingRunResponse"];
                };
            };
        };
    };
    get_training_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingRunRecord"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
